#ifndef BOGEYMAN_OPTIONS_HPP_
# define BOGEYMAN_OPTIONS_HPP_

// Possible definition for _BOGEYMAN_ACTION_ON_FAILURE
# define BOGEYMAN_ABORT_ON_FAILURE		0
# define BOGEYMAN_EXIT_ON_FAILURE		1
# define BOGEYMAN_LOG_ON_FAILURE        	2
# define BOGEYMAN_DO_NOTHING_ON_FAILURE		3

# define BOGEYMAN_DEFAULT_ACTION_ON_FAILURE	BOGEYMAN_ABORT_ON_FAILURE


// Possible definition for _BOGEYMAN_PRINT_ERROR_LINE
# define BOGEYMAN_PRINT_ERROR_LINE_TO_OUTPUT	0
# define BOGEYMAN_LOG_ERROR_LINE_TO_FILE        1
# define BOGEYMAN_DONT_PRINT_ERROR_LINE		2

# define BOGEYMAN_DEFAULT_PRINT_ERROR_LINE	BOGEYMAN_PRINT_ERROR_LINE_TO_OUTPUT

#endif // !BOGEYMAN_OPTIONS_HPP_
